# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: "Star Wars" }, { name: "Lord of the Rings" }])
#   Character.create(name: "Luke", movie: movies.first)
Question.create(title: '栄養バランスのとれた食事、心身のリフレッシュ、十分な休養が取れている')
Question.create(title: '完璧主義だと思う')
Question.create(title: '自分がどう思われるのか気になって仕方がない')
Question.create(title: '「こうあるべき」という自分の理想やものさしが明確にある')
Question.create(title: 'ストレスを感じやすい')
Question.create(title: '内向的な性格である')
Question.create(title: '一人の時間が持てない')
Question.create(title: '以前に比べて集中できなくなった')
Question.create(title: '「オフ」の時にも仕事や家庭のことを考える')
Question.create(title: '子供がいる')

FatigueType.create(name: '人間関係')
FatigueType.create(name: '不眠')
FatigueType.create(name: 'イライラ')
FatigueType.create(name: 'エネルギー不足')
FatigueType.create(name: 'ホルモンバランスの乱れ')
FatigueType.create(name: '育児')

UserAnswer.create(question_id: 1, answer: true, fatigue_type_id: 1, point: 1)
UserAnswer.create(question_id: 1, answer: true, fatigue_type_id: 2, point: 1)
UserAnswer.create(question_id: 1, answer: true, fatigue_type_id: 3, point: 1)
UserAnswer.create(question_id: 1, answer: true, fatigue_type_id: 4, point: 0)
UserAnswer.create(question_id: 1, answer: true, fatigue_type_id: 5, point: 0)
UserAnswer.create(question_id: 1, answer: true, fatigue_type_id: 6, point: 0)
UserAnswer.create(question_id: 1, answer: false, fatigue_type_id: 1, point: 0)
UserAnswer.create(question_id: 1, answer: false, fatigue_type_id: 2, point: 0)
UserAnswer.create(question_id: 1, answer: false, fatigue_type_id: 3, point: 0)
UserAnswer.create(question_id: 1, answer: false, fatigue_type_id: 4, point: 4)
UserAnswer.create(question_id: 1, answer: false, fatigue_type_id: 5, point: 3)
UserAnswer.create(question_id: 1, answer: false, fatigue_type_id: 6, point: 2)
UserAnswer.create(question_id: 2, answer: true, fatigue_type_id: 1, point: 1)
UserAnswer.create(question_id: 2, answer: true, fatigue_type_id: 2, point: 3)
UserAnswer.create(question_id: 2, answer: true, fatigue_type_id: 3, point: 2)
UserAnswer.create(question_id: 2, answer: true, fatigue_type_id: 4, point: 0)
UserAnswer.create(question_id: 2, answer: true, fatigue_type_id: 5, point: 0)
UserAnswer.create(question_id: 2, answer: true, fatigue_type_id: 6, point: 0)
UserAnswer.create(question_id: 2, answer: false, fatigue_type_id: 1, point: 0)
UserAnswer.create(question_id: 2, answer: false, fatigue_type_id: 2, point: 0)
UserAnswer.create(question_id: 2, answer: false, fatigue_type_id: 3, point: 0)
UserAnswer.create(question_id: 2, answer: false, fatigue_type_id: 4, point: 1)
UserAnswer.create(question_id: 2, answer: false, fatigue_type_id: 5, point: 0)
UserAnswer.create(question_id: 2, answer: false, fatigue_type_id: 6, point: 0)
UserAnswer.create(question_id: 3, answer: true, fatigue_type_id: 1, point: 4)
UserAnswer.create(question_id: 3, answer: true, fatigue_type_id: 2, point: 3)
UserAnswer.create(question_id: 3, answer: true, fatigue_type_id: 3, point: 0)
UserAnswer.create(question_id: 3, answer: true, fatigue_type_id: 4, point: 0)
UserAnswer.create(question_id: 3, answer: true, fatigue_type_id: 5, point: 2)
UserAnswer.create(question_id: 3, answer: true, fatigue_type_id: 6, point: 0)
UserAnswer.create(question_id: 3, answer: false, fatigue_type_id: 1, point: 0)
UserAnswer.create(question_id: 3, answer: false, fatigue_type_id: 2, point: 0)
UserAnswer.create(question_id: 3, answer: false, fatigue_type_id: 3, point: 1)
UserAnswer.create(question_id: 3, answer: false, fatigue_type_id: 4, point: 1)
UserAnswer.create(question_id: 3, answer: false, fatigue_type_id: 5, point: 0)
UserAnswer.create(question_id: 3, answer: false, fatigue_type_id: 6, point: 1)
UserAnswer.create(question_id: 4, answer: true, fatigue_type_id: 1, point: 0)
UserAnswer.create(question_id: 4, answer: true, fatigue_type_id: 2, point: 0)
UserAnswer.create(question_id: 4, answer: true, fatigue_type_id: 3, point: 3)
UserAnswer.create(question_id: 4, answer: true, fatigue_type_id: 4, point: 2)
UserAnswer.create(question_id: 4, answer: true, fatigue_type_id: 5, point: 0)
UserAnswer.create(question_id: 4, answer: true, fatigue_type_id: 6, point: 1)
UserAnswer.create(question_id: 4, answer: false, fatigue_type_id: 1, point: 1)
UserAnswer.create(question_id: 4, answer: false, fatigue_type_id: 2, point: 1)
UserAnswer.create(question_id: 4, answer: false, fatigue_type_id: 3, point: 0)
UserAnswer.create(question_id: 4, answer: false, fatigue_type_id: 4, point: 0)
UserAnswer.create(question_id: 4, answer: false, fatigue_type_id: 5, point: 1)
UserAnswer.create(question_id: 4, answer: false, fatigue_type_id: 6, point: 0)
UserAnswer.create(question_id: 5, answer: true, fatigue_type_id: 1, point: 2)
UserAnswer.create(question_id: 5, answer: true, fatigue_type_id: 2, point: 1)
UserAnswer.create(question_id: 5, answer: true, fatigue_type_id: 3, point: 3)
UserAnswer.create(question_id: 5, answer: true, fatigue_type_id: 4, point: 0)
UserAnswer.create(question_id: 5, answer: true, fatigue_type_id: 5, point: 3)
UserAnswer.create(question_id: 5, answer: true, fatigue_type_id: 6, point: 0)
UserAnswer.create(question_id: 5, answer: false, fatigue_type_id: 1, point: 0)
UserAnswer.create(question_id: 5, answer: false, fatigue_type_id: 2, point: 0)
UserAnswer.create(question_id: 5, answer: false, fatigue_type_id: 3, point: 0)
UserAnswer.create(question_id: 5, answer: false, fatigue_type_id: 4, point: 1)
UserAnswer.create(question_id: 5, answer: false, fatigue_type_id: 5, point: 0)
UserAnswer.create(question_id: 5, answer: false, fatigue_type_id: 6, point: 0)
UserAnswer.create(question_id: 6, answer: true, fatigue_type_id: 1, point: 3)
UserAnswer.create(question_id: 6, answer: true, fatigue_type_id: 2, point: 0)
UserAnswer.create(question_id: 6, answer: true, fatigue_type_id: 3, point: 0)
UserAnswer.create(question_id: 6, answer: true, fatigue_type_id: 4, point: 2)
UserAnswer.create(question_id: 6, answer: true, fatigue_type_id: 5, point: 0)
UserAnswer.create(question_id: 6, answer: true, fatigue_type_id: 6, point: 0)
UserAnswer.create(question_id: 6, answer: false, fatigue_type_id: 1, point: 0)
UserAnswer.create(question_id: 6, answer: false, fatigue_type_id: 2, point: 0)
UserAnswer.create(question_id: 6, answer: false, fatigue_type_id: 3, point: 0)
UserAnswer.create(question_id: 6, answer: false, fatigue_type_id: 4, point: 0)
UserAnswer.create(question_id: 6, answer: false, fatigue_type_id: 5, point: 0)
UserAnswer.create(question_id: 6, answer: false, fatigue_type_id: 6, point: 0)
UserAnswer.create(question_id: 7, answer: true, fatigue_type_id: 1, point: 0)
UserAnswer.create(question_id: 7, answer: true, fatigue_type_id: 2, point: 0)
UserAnswer.create(question_id: 7, answer: true, fatigue_type_id: 3, point: 2)
UserAnswer.create(question_id: 7, answer: true, fatigue_type_id: 4, point: 0)
UserAnswer.create(question_id: 7, answer: true, fatigue_type_id: 5, point: 0)
UserAnswer.create(question_id: 7, answer: true, fatigue_type_id: 6, point: 3)
UserAnswer.create(question_id: 7, answer: false, fatigue_type_id: 1, point: 0)
UserAnswer.create(question_id: 7, answer: false, fatigue_type_id: 2, point: 0)
UserAnswer.create(question_id: 7, answer: false, fatigue_type_id: 3, point: 0)
UserAnswer.create(question_id: 7, answer: false, fatigue_type_id: 4, point: 1)
UserAnswer.create(question_id: 7, answer: false, fatigue_type_id: 5, point: 1)
UserAnswer.create(question_id: 7, answer: false, fatigue_type_id: 6, point: 0)
UserAnswer.create(question_id: 8, answer: true, fatigue_type_id: 1, point: 0)
UserAnswer.create(question_id: 8, answer: true, fatigue_type_id: 2, point: 1)
UserAnswer.create(question_id: 8, answer: true, fatigue_type_id: 3, point: 0)
UserAnswer.create(question_id: 8, answer: true, fatigue_type_id: 4, point: 3)
UserAnswer.create(question_id: 8, answer: true, fatigue_type_id: 5, point: 2)
UserAnswer.create(question_id: 8, answer: true, fatigue_type_id: 6, point: 0)
UserAnswer.create(question_id: 8, answer: false, fatigue_type_id: 1, point: 0)
UserAnswer.create(question_id: 8, answer: false, fatigue_type_id: 2, point: 0)
UserAnswer.create(question_id: 8, answer: false, fatigue_type_id: 3, point: 0)
UserAnswer.create(question_id: 8, answer: false, fatigue_type_id: 4, point: 0)
UserAnswer.create(question_id: 8, answer: false, fatigue_type_id: 5, point: 0)
UserAnswer.create(question_id: 8, answer: false, fatigue_type_id: 6, point: 0)
UserAnswer.create(question_id: 9, answer: true, fatigue_type_id: 1, point: 2)
UserAnswer.create(question_id: 9, answer: true, fatigue_type_id: 2, point: 3)
UserAnswer.create(question_id: 9, answer: true, fatigue_type_id: 3, point: 1)
UserAnswer.create(question_id: 9, answer: true, fatigue_type_id: 4, point: 0)
UserAnswer.create(question_id: 9, answer: true, fatigue_type_id: 5, point: 0)
UserAnswer.create(question_id: 9, answer: true, fatigue_type_id: 6, point: 0)
UserAnswer.create(question_id: 9, answer: false, fatigue_type_id: 1, point: 0)
UserAnswer.create(question_id: 9, answer: false, fatigue_type_id: 2, point: 0)
UserAnswer.create(question_id: 9, answer: false, fatigue_type_id: 3, point: 0)
UserAnswer.create(question_id: 9, answer: false, fatigue_type_id: 4, point: 1)
UserAnswer.create(question_id: 9, answer: false, fatigue_type_id: 5, point: 1)
UserAnswer.create(question_id: 9, answer: false, fatigue_type_id: 6, point: 0)
UserAnswer.create(question_id: 10, answer: true, fatigue_type_id: 1, point: 0)
UserAnswer.create(question_id: 10, answer: true, fatigue_type_id: 2, point: 0)
UserAnswer.create(question_id: 10, answer: true, fatigue_type_id: 3, point: 0)
UserAnswer.create(question_id: 10, answer: true, fatigue_type_id: 4, point: 0)
UserAnswer.create(question_id: 10, answer: true, fatigue_type_id: 5, point: 0)
UserAnswer.create(question_id: 10, answer: true, fatigue_type_id: 6, point: 5)
UserAnswer.create(question_id: 10, answer: false, fatigue_type_id: 1, point: 0)
UserAnswer.create(question_id: 10, answer: false, fatigue_type_id: 2, point: 0)
UserAnswer.create(question_id: 10, answer: false, fatigue_type_id: 3, point: 0)
UserAnswer.create(question_id: 10, answer: false, fatigue_type_id: 4, point: 1)
UserAnswer.create(question_id: 10, answer: false, fatigue_type_id: 5, point: 0)
UserAnswer.create(question_id: 10, answer: false, fatigue_type_id: 6, point: 0)

Aroma.create(fatigue_type_id: 1, name: "柑橘系")
Aroma.create(fatigue_type_id: 2, name: "ラベンダー")
Aroma.create(fatigue_type_id: 3, name: "カモミール")
Aroma.create(fatigue_type_id: 4, name: "ペパーミント")
Aroma.create(fatigue_type_id: 5, name: "イランイラン")
Aroma.create(fatigue_type_id: 6, name: "ゼラニウム")

Manga.create(fatigue_type_id: 1, title: "葬送のフリーレン")
Manga.create(fatigue_type_id: 1, title: "それでも町は廻っている")
Manga.create(fatigue_type_id: 1, title: "舞妓さんちのまかないさん")
Manga.create(fatigue_type_id: 2, title: "ひらやすみ")
Manga.create(fatigue_type_id: 2, title: "君は放課後のインソムニア")
Manga.create(fatigue_type_id: 2, title: "舞妓さんちのまかないさん")
Manga.create(fatigue_type_id: 3, title: "善悪の屑")
Manga.create(fatigue_type_id: 3, title: "闇金ウシジマくん")
Manga.create(fatigue_type_id: 3, title: "前科者")
Manga.create(fatigue_type_id: 4, title: "ハイキュー")
Manga.create(fatigue_type_id: 4, title: "アイシールド21")
Manga.create(fatigue_type_id: 4, title: "ブルーピリオド")
Manga.create(fatigue_type_id: 5, title: "アシガール")
Manga.create(fatigue_type_id: 5, title: "スキップとローファー")
Manga.create(fatigue_type_id: 5, title: "その着せ替え人形は恋をする")
Manga.create(fatigue_type_id: 5, title: "僕の心のヤバいやつ")
Manga.create(fatigue_type_id: 6, title: "リエゾン-こどものこころ診療所")
Manga.create(fatigue_type_id: 6, title: "コウノドリ")
Manga.create(fatigue_type_id: 6, title: "ゴールデンカムイ")
Manga.create(fatigue_type_id: 6, title: "幸せは食べて寝て待て")
