class CreateUserAnswers < ActiveRecord::Migration[7.0]
  def change
    create_table :user_answers do |t|
      t.references :question, null: false, foreign_key: true
      t.boolean :answer
      t.references :fatigue_type, null: false, foreign_key: true
      t.integer :point

      t.timestamps
    end
    UserAnswer.create(question_id: 1, answer: true, fatigue_type_id: 1, point: 1)
    UserAnswer.create(question_id: 1, answer: true, fatigue_type_id: 2, point: 1)
    UserAnswer.create(question_id: 1, answer: true, fatigue_type_id: 3, point: 1)
    UserAnswer.create(question_id: 1, answer: true, fatigue_type_id: 4, point: 0)
    UserAnswer.create(question_id: 1, answer: true, fatigue_type_id: 5, point: 0)
    UserAnswer.create(question_id: 1, answer: true, fatigue_type_id: 6, point: 0)
    UserAnswer.create(question_id: 1, answer: false, fatigue_type_id: 1, point: 0)
    UserAnswer.create(question_id: 1, answer: false, fatigue_type_id: 2, point: 0)
    UserAnswer.create(question_id: 1, answer: false, fatigue_type_id: 3, point: 0)
    UserAnswer.create(question_id: 1, answer: false, fatigue_type_id: 4, point: 4)
    UserAnswer.create(question_id: 1, answer: false, fatigue_type_id: 5, point: 3)
    UserAnswer.create(question_id: 1, answer: false, fatigue_type_id: 6, point: 2)

    UserAnswer.create(question_id: 2, answer: true, fatigue_type_id: 1, point: 1)
    UserAnswer.create(question_id: 2, answer: true, fatigue_type_id: 2, point: 3)
    UserAnswer.create(question_id: 2, answer: true, fatigue_type_id: 3, point: 2)
    UserAnswer.create(question_id: 2, answer: true, fatigue_type_id: 4, point: 0)
    UserAnswer.create(question_id: 2, answer: true, fatigue_type_id: 5, point: 0)
    UserAnswer.create(question_id: 2, answer: true, fatigue_type_id: 6, point: 0)
    UserAnswer.create(question_id: 2, answer: false, fatigue_type_id: 1, point: 0)
    UserAnswer.create(question_id: 2, answer: false, fatigue_type_id: 2, point: 0)
    UserAnswer.create(question_id: 2, answer: false, fatigue_type_id: 3, point: 0)
    UserAnswer.create(question_id: 2, answer: false, fatigue_type_id: 4, point: 1)
    UserAnswer.create(question_id: 2, answer: false, fatigue_type_id: 5, point: 0)
    UserAnswer.create(question_id: 2, answer: false, fatigue_type_id: 6, point: 0)

    UserAnswer.create(question_id: 3, answer: true, fatigue_type_id: 1, point: 4)
    UserAnswer.create(question_id: 3, answer: true, fatigue_type_id: 2, point: 3)
    UserAnswer.create(question_id: 3, answer: true, fatigue_type_id: 3, point: 0)
    UserAnswer.create(question_id: 3, answer: true, fatigue_type_id: 4, point: 0)
    UserAnswer.create(question_id: 3, answer: true, fatigue_type_id: 5, point: 2)
    UserAnswer.create(question_id: 3, answer: true, fatigue_type_id: 6, point: 0)
    UserAnswer.create(question_id: 3, answer: false, fatigue_type_id: 1, point: 0)
    UserAnswer.create(question_id: 3, answer: false, fatigue_type_id: 2, point: 0)
    UserAnswer.create(question_id: 3, answer: false, fatigue_type_id: 3, point: 1)
    UserAnswer.create(question_id: 3, answer: false, fatigue_type_id: 4, point: 1)
    UserAnswer.create(question_id: 3, answer: false, fatigue_type_id: 5, point: 0)
    UserAnswer.create(question_id: 3, answer: false, fatigue_type_id: 6, point: 1)

    UserAnswer.create(question_id: 4, answer: true, fatigue_type_id: 1, point: 0)
    UserAnswer.create(question_id: 4, answer: true, fatigue_type_id: 2, point: 0)
    UserAnswer.create(question_id: 4, answer: true, fatigue_type_id: 3, point: 3)
    UserAnswer.create(question_id: 4, answer: true, fatigue_type_id: 4, point: 2)
    UserAnswer.create(question_id: 4, answer: true, fatigue_type_id: 5, point: 0)
    UserAnswer.create(question_id: 4, answer: true, fatigue_type_id: 6, point: 1)
    UserAnswer.create(question_id: 4, answer: false, fatigue_type_id: 1, point: 1)
    UserAnswer.create(question_id: 4, answer: false, fatigue_type_id: 2, point: 1)
    UserAnswer.create(question_id: 4, answer: false, fatigue_type_id: 3, point: 0)
    UserAnswer.create(question_id: 4, answer: false, fatigue_type_id: 4, point: 0)
    UserAnswer.create(question_id: 4, answer: false, fatigue_type_id: 5, point: 1)
    UserAnswer.create(question_id: 4, answer: false, fatigue_type_id: 6, point: 0)

    UserAnswer.create(question_id: 5, answer: true, fatigue_type_id: 1, point: 2)
    UserAnswer.create(question_id: 5, answer: true, fatigue_type_id: 2, point: 1)
    UserAnswer.create(question_id: 5, answer: true, fatigue_type_id: 3, point: 3)
    UserAnswer.create(question_id: 5, answer: true, fatigue_type_id: 4, point: 0)
    UserAnswer.create(question_id: 5, answer: true, fatigue_type_id: 5, point: 3)
    UserAnswer.create(question_id: 5, answer: true, fatigue_type_id: 6, point: 0)
    UserAnswer.create(question_id: 5, answer: false, fatigue_type_id: 1, point: 0)
    UserAnswer.create(question_id: 5, answer: false, fatigue_type_id: 2, point: 0)
    UserAnswer.create(question_id: 5, answer: false, fatigue_type_id: 3, point: 0)
    UserAnswer.create(question_id: 5, answer: false, fatigue_type_id: 4, point: 1)
    UserAnswer.create(question_id: 5, answer: false, fatigue_type_id: 5, point: 0)
    UserAnswer.create(question_id: 5, answer: false, fatigue_type_id: 6, point: 0)

    UserAnswer.create(question_id: 6, answer: true, fatigue_type_id: 1, point: 3)
    UserAnswer.create(question_id: 6, answer: true, fatigue_type_id: 2, point: 0)
    UserAnswer.create(question_id: 6, answer: true, fatigue_type_id: 3, point: 0)
    UserAnswer.create(question_id: 6, answer: true, fatigue_type_id: 4, point: 2)
    UserAnswer.create(question_id: 6, answer: true, fatigue_type_id: 5, point: 0)
    UserAnswer.create(question_id: 6, answer: true, fatigue_type_id: 6, point: 0)
    UserAnswer.create(question_id: 6, answer: false, fatigue_type_id: 1, point: 0)
    UserAnswer.create(question_id: 6, answer: false, fatigue_type_id: 2, point: 0)
    UserAnswer.create(question_id: 6, answer: false, fatigue_type_id: 3, point: 0)
    UserAnswer.create(question_id: 6, answer: false, fatigue_type_id: 4, point: 0)
    UserAnswer.create(question_id: 6, answer: false, fatigue_type_id: 5, point: 0)
    UserAnswer.create(question_id: 6, answer: false, fatigue_type_id: 6, point: 0)

    UserAnswer.create(question_id: 7, answer: true, fatigue_type_id: 1, point: 0)
    UserAnswer.create(question_id: 7, answer: true, fatigue_type_id: 2, point: 0)
    UserAnswer.create(question_id: 7, answer: true, fatigue_type_id: 3, point: 2)
    UserAnswer.create(question_id: 7, answer: true, fatigue_type_id: 4, point: 0)
    UserAnswer.create(question_id: 7, answer: true, fatigue_type_id: 5, point: 0)
    UserAnswer.create(question_id: 7, answer: true, fatigue_type_id: 6, point: 3)
    UserAnswer.create(question_id: 7, answer: false, fatigue_type_id: 1, point: 0)
    UserAnswer.create(question_id: 7, answer: false, fatigue_type_id: 2, point: 0)
    UserAnswer.create(question_id: 7, answer: false, fatigue_type_id: 3, point: 0)
    UserAnswer.create(question_id: 7, answer: false, fatigue_type_id: 4, point: 1)
    UserAnswer.create(question_id: 7, answer: false, fatigue_type_id: 5, point: 1)
    UserAnswer.create(question_id: 7, answer: false, fatigue_type_id: 6, point: 0)

    UserAnswer.create(question_id: 8, answer: true, fatigue_type_id: 1, point: 0)
    UserAnswer.create(question_id: 8, answer: true, fatigue_type_id: 2, point: 1)
    UserAnswer.create(question_id: 8, answer: true, fatigue_type_id: 3, point: 0)
    UserAnswer.create(question_id: 8, answer: true, fatigue_type_id: 4, point: 3)
    UserAnswer.create(question_id: 8, answer: true, fatigue_type_id: 5, point: 2)
    UserAnswer.create(question_id: 8, answer: true, fatigue_type_id: 6, point: 0)
    UserAnswer.create(question_id: 8, answer: false, fatigue_type_id: 1, point: 0)
    UserAnswer.create(question_id: 8, answer: false, fatigue_type_id: 2, point: 0)
    UserAnswer.create(question_id: 8, answer: false, fatigue_type_id: 3, point: 0)
    UserAnswer.create(question_id: 8, answer: false, fatigue_type_id: 4, point: 0)
    UserAnswer.create(question_id: 8, answer: false, fatigue_type_id: 5, point: 0)
    UserAnswer.create(question_id: 8, answer: false, fatigue_type_id: 6, point: 0)

    UserAnswer.create(question_id: 9, answer: true, fatigue_type_id: 1, point: 2)
    UserAnswer.create(question_id: 9, answer: true, fatigue_type_id: 2, point: 3)
    UserAnswer.create(question_id: 9, answer: true, fatigue_type_id: 3, point: 1)
    UserAnswer.create(question_id: 9, answer: true, fatigue_type_id: 4, point: 0)
    UserAnswer.create(question_id: 9, answer: true, fatigue_type_id: 5, point: 0)
    UserAnswer.create(question_id: 9, answer: true, fatigue_type_id: 6, point: 0)
    UserAnswer.create(question_id: 9, answer: false, fatigue_type_id: 1, point: 0)
    UserAnswer.create(question_id: 9, answer: false, fatigue_type_id: 2, point: 0)
    UserAnswer.create(question_id: 9, answer: false, fatigue_type_id: 3, point: 0)
    UserAnswer.create(question_id: 9, answer: false, fatigue_type_id: 4, point: 1)
    UserAnswer.create(question_id: 9, answer: false, fatigue_type_id: 5, point: 1)
    UserAnswer.create(question_id: 9, answer: false, fatigue_type_id: 6, point: 0)

    UserAnswer.create(question_id: 10, answer: true, fatigue_type_id: 1, point: 0)
    UserAnswer.create(question_id: 10, answer: true, fatigue_type_id: 2, point: 0)
    UserAnswer.create(question_id: 10, answer: true, fatigue_type_id: 3, point: 0)
    UserAnswer.create(question_id: 10, answer: true, fatigue_type_id: 4, point: 0)
    UserAnswer.create(question_id: 10, answer: true, fatigue_type_id: 5, point: 0)
    UserAnswer.create(question_id: 10, answer: true, fatigue_type_id: 6, point: 5)
    UserAnswer.create(question_id: 10, answer: false, fatigue_type_id: 1, point: 0)
    UserAnswer.create(question_id: 10, answer: false, fatigue_type_id: 2, point: 0)
    UserAnswer.create(question_id: 10, answer: false, fatigue_type_id: 3, point: 0)
    UserAnswer.create(question_id: 10, answer: false, fatigue_type_id: 4, point: 1)
    UserAnswer.create(question_id: 10, answer: false, fatigue_type_id: 5, point: 0)
    UserAnswer.create(question_id: 10, answer: false, fatigue_type_id: 6, point: 0)
  end
end
